# Generated by Django 5.0.4 on 2024-05-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('album', 'img')},
        ),
    ]
