# Generated by Django 5.0.4 on 2024-05-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_img_alter_photo_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
    ]
