# Generated by Django 5.0.4 on 2024-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_album_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
