# Generated by Django 5.0.4 on 2024-05-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_alter_rating_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='photo_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='photo_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('photo_name', 'photo_size')},
        ),
    ]
